import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  es: {
    skipToContent: 'Ir al contenido',
    mainNavigation: 'Navegación principal',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    collapseMenu: 'Contraer menú',
    expandMenu: 'Expandir menú',
    account: 'Mi cuenta',
    appearance: 'Apariencia',
    changePhoto: 'Cambiar foto de perfil',
    classroom: 'Aula',
    quickActions: 'Accesos rápidos',
    noUpcoming: 'No hay fechas próximas registradas.',
    noAssignments: 'Aún no hay asignaciones publicadas para tu cuenta.',
    pipelineCopy: 'Estado general del trabajo académico de tus comisiones.',
    agendaCopy: 'Fechas de entrega ordenadas por prioridad.',
    recentCopy: 'Acceso directo a las tareas publicadas, su rúbrica y su estado de entrega.',
    loadError: 'No se pudo cargar el panel. Revisa tu conexión e inténtalo de nuevo.',
    generalRoom: 'Aula general',
    viewDetail: 'Ver detalle',
    panel: 'Panel',
    commissions: 'Comisiones',
    tasks: 'Tareas',
    alerts: 'Avisos',
    model: 'Modelo de Naciones Unidas',
    sidebarIntro: 'Aula académica para comisiones, rúbricas, entregas y seguimiento de delegados.',
    light: 'Claro',
    dark: 'Oscuro',
    profile: 'Perfil',
    editProfile: 'Editar perfil',
    fullName: 'Nombre completo',
    save: 'Guardar cambios',
    logout: 'Cerrar sesión',
    showMenu: 'Mostrar menú',
    hideMenu: 'Ocultar menú',
    language: 'Idioma',
    academicProgram: 'Programa académico MINUME XVII',
    enter: 'Ingresar',
    virtualRoom: 'Aula virtual académica',
    homeCopy: 'Un espacio profesional para que mesas directivas y delegados gestionen tareas, rúbricas, reuniones, foros y entregas desde un solo portal.',
    enterOrRegister: 'Entrar o registrarme',
    seePlatform: 'Ver plataforma',
    roomPreview: 'Trabajo activo',
    roomPreviewText: 'Rúbrica publicada, reunión programada y entregas en seguimiento.',
    allAsRoom: 'Todo visible como aula',
    dashboardHeadline: 'Dashboard inmediato para delegados y mesa directiva',
    rubricsAssignments: 'Rúbricas y asignaciones',
    rubricHeadline: 'Las mesas pueden publicar tareas con criterios y puntaje',
    meetingsHeadline: 'Calendario, enlaces, participación y grabaciones',
    welcomeBack: 'Bienvenido de nuevo',
    newAccount: 'Nueva cuenta',
    loginTitle: 'Entrar a MINUME ROOM',
    registerTitle: 'Registrarme como delegado',
    loginCopy: 'Usa tu correo y contraseña para entrar al panel académico.',
    registerCopy: 'Crea tu cuenta de delegado y accede al dashboard de inmediato.',
    email: 'Correo electrónico',
    password: 'Contraseña',
    minPassword: 'Mínimo 6 caracteres',
    login: 'Iniciar sesión',
    register: 'Registro',
    processing: 'Procesando...',
    enterPanel: 'Entrar al panel',
    createAccount: 'Crear cuenta y entrar',
    academicCenter: 'Centro académico',
    greetingMorning: 'Buenos días',
    greetingAfternoon: 'Buenas tardes',
    greetingNight: 'Buenas noches',
    dashboardCopy: 'Aquí tienes tus comisiones, tareas, entregas y calificaciones en un solo lugar.',
    visibleCommissions: 'Comisiones visibles',
    activeTasks: 'Tareas activas',
    deliveryRate: 'Tasa de entrega',
    pendingAlerts: 'Avisos pendientes',
    taskRhythm: 'Ritmo de tareas',
    upcomingAgenda: 'Agenda próxima',
    recentAssignments: 'Asignaciones recientes',
    viewAll: 'Ver todas',
    assignmentDetail: 'Detalle de asignación',
    assignmentDetailCopy: 'Consulta completa del encargo, su objetivo, la rúbrica y el estado de entrega.',
    commission: 'Comisión',
    code: 'Código',
    type: 'Tipo',
    status: 'Estado',
    deadline: 'Plazo',
    description: 'Descripción',
    objective: 'Objetivo',
    rubric: 'Rúbrica de evaluación',
    rubricCopy: 'La mesa directiva evaluará esta tarea con los criterios publicados.',
    criterion: 'Criterio',
    points: 'Puntos',
    submitDocument: 'Enviar documento',
    submitDocumentCopy: 'Adjunta un PDF, documento de Office o cualquier archivo relevante. Si vuelves a enviar, tu entrega anterior será reemplazada.',
    upload: 'Enviar documento',
    uploading: 'Subiendo...',
    mySubmission: 'Mi entrega',
    receivedSubmissions: 'Entregas recibidas',
    viewFile: 'Ver archivo',
    grade: 'Calificar',
    returnTask: 'Devolver tarea',
    score: 'Calificación',
    feedback: 'Retroalimentación'
  },
  en: {
    skipToContent: 'Skip to content',
    mainNavigation: 'Main navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    collapseMenu: 'Collapse menu',
    expandMenu: 'Expand menu',
    account: 'My account',
    appearance: 'Appearance',
    changePhoto: 'Change profile picture',
    classroom: 'Classroom',
    quickActions: 'Quick links',
    noUpcoming: 'No upcoming deadlines yet.',
    noAssignments: 'No assignments published for your account yet.',
    pipelineCopy: 'Overall status of the academic work in your committees.',
    agendaCopy: 'Deadlines sorted by priority.',
    recentCopy: 'Direct access to published tasks, their rubric, and submission status.',
    loadError: 'The panel could not be loaded. Check your connection and try again.',
    generalRoom: 'General room',
    viewDetail: 'View detail',
    panel: 'Panel',
    commissions: 'Committees',
    tasks: 'Tasks',
    alerts: 'Alerts',
    model: 'Model United Nations',
    sidebarIntro: 'Academic room for committees, rubrics, submissions, and delegate tracking.',
    light: 'Light',
    dark: 'Dark',
    profile: 'Profile',
    editProfile: 'Edit profile',
    fullName: 'Full name',
    save: 'Save changes',
    logout: 'Log out',
    showMenu: 'Show menu',
    hideMenu: 'Hide menu',
    language: 'Language',
    academicProgram: 'MINUME XVII Academic Program',
    enter: 'Enter',
    virtualRoom: 'Academic virtual room',
    homeCopy: 'A professional space for chairs and delegates to manage tasks, rubrics, meetings, forums, and submissions from one portal.',
    enterOrRegister: 'Enter or register',
    seePlatform: 'View platform',
    roomPreview: 'Active work',
    roomPreviewText: 'Rubric published, meeting scheduled, and submissions under review.',
    allAsRoom: 'Everything visible as a room',
    dashboardHeadline: 'Immediate dashboard for delegates and chairs',
    rubricsAssignments: 'Rubrics and assignments',
    rubricHeadline: 'Chairs can publish tasks with criteria and scores',
    meetingsHeadline: 'Calendar, links, attendance, and recordings',
    welcomeBack: 'Welcome back',
    newAccount: 'New account',
    loginTitle: 'Enter MINUME ROOM',
    registerTitle: 'Register as delegate',
    loginCopy: 'Use your email and password to enter the academic panel.',
    registerCopy: 'Create your delegate account and access the dashboard immediately.',
    email: 'Email',
    password: 'Password',
    minPassword: 'Minimum 6 characters',
    login: 'Sign in',
    register: 'Register',
    processing: 'Processing...',
    enterPanel: 'Enter panel',
    createAccount: 'Create account and enter',
    academicCenter: 'Academic center',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingNight: 'Good evening',
    dashboardCopy: 'Your committees, tasks, submissions, and grades in one place.',
    visibleCommissions: 'Visible committees',
    activeTasks: 'Active tasks',
    deliveryRate: 'Submission rate',
    pendingAlerts: 'Pending alerts',
    taskRhythm: 'Task rhythm',
    upcomingAgenda: 'Upcoming agenda',
    recentAssignments: 'Recent assignments',
    viewAll: 'View all',
    assignmentDetail: 'Assignment detail',
    assignmentDetailCopy: 'Full view of the task, objective, rubric, and submission status.',
    commission: 'Committee',
    code: 'Code',
    type: 'Type',
    status: 'Status',
    deadline: 'Deadline',
    description: 'Description',
    objective: 'Objective',
    rubric: 'Evaluation rubric',
    rubricCopy: 'The chair team will evaluate this task using the published criteria.',
    criterion: 'Criterion',
    points: 'Points',
    submitDocument: 'Submit document',
    submitDocumentCopy: 'Attach a PDF, Office document, or relevant file. If you resubmit, your previous submission will be replaced.',
    upload: 'Submit document',
    uploading: 'Uploading...',
    mySubmission: 'My submission',
    receivedSubmissions: 'Received submissions',
    viewFile: 'View file',
    grade: 'Grade',
    returnTask: 'Return task',
    score: 'Score',
    feedback: 'Feedback'
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('minume-language') || 'es');

  useEffect(() => {
    localStorage.setItem('minume-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || translations.es[key] || key
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
